/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirgrapik;

/**
 *
 * @author Mea
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuA = new javax.swing.JMenu();
        menuItemFileTentang = new javax.swing.JMenuItem();
        menuItemFileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemPT01A = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemPT04A = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemPT05A = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemPT06A = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemPT07A = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemPT08A = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuItemPT09A = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuItemPT10A = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuItemPT11A = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuItemPT12A = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuItemPT13A = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuItemPT14A = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuA.setText("File");

        menuItemFileTentang.setText("Tentang");
        menuA.add(menuItemFileTentang);

        menuItemFileExit.setText("Exit");
        menuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFileExitActionPerformed(evt);
            }
        });
        menuA.add(menuItemFileExit);

        jMenuBar1.add(menuA);

        jMenu2.setText("PT 3");

        menuItemPT01A.setText("Latihan Ke 1");
        jMenu2.add(menuItemPT01A);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("PT 4");

        menuItemPT04A.setText("Latihan Ke ");
        jMenu3.add(menuItemPT04A);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PT 5");

        menuItemPT05A.setText("Latihan Ke ");
        jMenu4.add(menuItemPT05A);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("PT 6");

        menuItemPT06A.setText("Latihan Ke ");
        jMenu5.add(menuItemPT06A);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("PT 7");

        menuItemPT07A.setText("Latihan Ke ");
        jMenu6.add(menuItemPT07A);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("PT 8");

        menuItemPT08A.setText("Latihan Ke ");
        jMenu7.add(menuItemPT08A);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("PT 9");

        menuItemPT09A.setText("Latihan Ke ");
        jMenu8.add(menuItemPT09A);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("PT 10");

        menuItemPT10A.setText("Latihan Ke ");
        jMenu9.add(menuItemPT10A);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("PT 11");

        menuItemPT11A.setText("Latihan Ke ");
        jMenu10.add(menuItemPT11A);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("PT 12");

        menuItemPT12A.setText("Latihan Ke ");
        jMenu11.add(menuItemPT12A);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("PT 13");

        menuItemPT13A.setText("Latihan Ke ");
        jMenu12.add(menuItemPT13A);

        jMenuBar1.add(jMenu12);

        jMenu13.setText("PT 14");

        menuItemPT14A.setText("Latihan Ke ");
        jMenu13.add(menuItemPT14A);

        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFileExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_menuItemFileExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuA;
    private javax.swing.JMenuItem menuItemFileExit;
    private javax.swing.JMenuItem menuItemFileTentang;
    private javax.swing.JMenuItem menuItemPT01A;
    private javax.swing.JMenuItem menuItemPT04A;
    private javax.swing.JMenuItem menuItemPT05A;
    private javax.swing.JMenuItem menuItemPT06A;
    private javax.swing.JMenuItem menuItemPT07A;
    private javax.swing.JMenuItem menuItemPT08A;
    private javax.swing.JMenuItem menuItemPT09A;
    private javax.swing.JMenuItem menuItemPT10A;
    private javax.swing.JMenuItem menuItemPT11A;
    private javax.swing.JMenuItem menuItemPT12A;
    private javax.swing.JMenuItem menuItemPT13A;
    private javax.swing.JMenuItem menuItemPT14A;
    // End of variables declaration//GEN-END:variables
}
